allow_remote_control yes
copy_on_select clipboard
cursor_trail 1
font_family family=MonoLisa features=-liga
font_size 22
hide_window_decorations titlebar-only
listen_on unix:/tmp/kitty
macos_colorspace displayp3
macos_option_as_alt both
macos_quit_when_last_window_closed yes
modify_font cell_height 8px
modify_font cell_width -2px
notify_on_cmd_finish invisible
scrollback_pager_history_size 10
shell_integration no-title
window_padding_width 8

# gruvbox-material dark mix
background #1d2021
foreground #e2cca9
selection_background #e9b143
selection_foreground #1d2021
cursor #e2cca9
cursor_text_color #1d2021
color0 #504945
color1 #f2594b
color2 #b0b846
color3 #e9b143
color4 #80aa9e
color5 #d3869b
color6 #8bba7f
color7 #e2cca9
color8 #a89984
active_border_color #504945
inactive_border_color #504945
active_tab_foreground #e2cca9
active_tab_background #1d2021
active_tab_font_style bold
inactive_tab_foreground #a89984
inactive_tab_background #1d2021

tab_activity_symbol *
tab_bar_style separator
tab_separator ""
tab_title_template "
  \ {fmt.fg._f28534}{sub.index}{fmt.fg.tab}
  \{('@'+title.split(' ')[0][1:-1]+'/')
    \if title[0] == '(' and '(macbookpro)' not in title else '' }
  \{title.split(' ')[-1].split('/')[-1]}
  \{sup.num_windows if num_windows > 1 else ''}
  \{activity_symbol}{bell_symbol}{tab.progress_percent} "
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5

enabled_layouts fat:bias=65,tall,vertical,stack
map cmd+enter launch --cwd current --location last
map cmd+f toggle_fullscreen
map cmd+z toggle_layout stack
map cmd+o send_text all /Users/ryan/Downloads/\e[Hkitten transfer  \e[D

# Move between panes/splits
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

# Resize panes/splits
map ctrl+alt+j kitten relative_resize.py down  3
map ctrl+alt+k kitten relative_resize.py up    3
map ctrl+alt+h kitten relative_resize.py left  3
map ctrl+alt+l kitten relative_resize.py right 3
map --when-focus-on var:IS_NVIM ctrl+alt+j
map --when-focus-on var:IS_NVIM ctrl+alt+k
map --when-focus-on var:IS_NVIM ctrl+alt+h
map --when-focus-on var:IS_NVIM ctrl+alt+l
map ctrl+alt+0 resize_window reset

# Rotate panes/splits
map kitty_mod+j move_window_forward
map kitty_mod+k move_window_backward

# Move window
map kitty_mod+m detach_window ask

# Scrollback
map cmd+p kitten hints --type word --program -
map shift+cmd+P kitten hints --type word --program @
map kitty_mod+h kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
